export const data = {
  products: [
    {
      _id: "1",
      name: "Chair",
      category: "furniture",
      image: "/images/products/product1.jpg",
      price: 120,
      countInStock: 0,
      rating: 4.5,
      numReviews: 9,
      description:
        "Chair to comfortable seat with wheels, high quality product",
    },
    {
      _id: "8",
      name: "HeadPhone",
      category: "accesories",
      image: "/images/products/product8.jpg",
      price: 20,
      countInStock: 4,
      rating: 5,
      numReviews: 4,
      description:
        "HeadPhone to hear good music, high quality product, clear sound",
    },

    {
      _id: "3",
      name: "Table",
      category: "furniture",
      image: "/images/products/product3.jpg",
      price: 50,
      countInStock: 2,
      rating: 4,
      numReviews: 10,
      description: "Table with wheels, high quality product, many uses",
    },
    {
      _id: "4",
      name: "Mobile Holder",
      category: "accesories",
      image: "/images/products/product4.jpg",
      price: 10,
      countInStock: 0,
      rating: 4.5,
      numReviews: 8,
      description: "Mobile Holder to hold phone, high quality product",
    },
    {
      _id: "5",
      name: "Boiler",
      category: "furniture",
      image: "/images/products/product5.jpg",
      price: 30,
      countInStock: 5,
      rating: 4,
      numReviews: 11,
      description: "Boiler to boil water, high quality product, fast heat",
    },
    {
      _id: "6",
      name: "Screen Holder",
      category: "accesories",
      image: "/images/products/product6.jpg",
      price: 220,
      countInStock: 3,
      rating: 4.5,
      numReviews: 8,
      description:
        "Screen Holder to hold screen, high quality product, can move in many directions",
    },
    {
      _id: "7",
      name: "Electric Heater",
      category: "furniture",
      image: "/images/products/product7.jpg",
      price: 120,
      countInStock: 0,
      rating: 4,
      numReviews: 8,
      description:
        "Electric Heater to make you feel hot, high quality product, use it in cold weather",
    },
    {
      _id: "2",
      name: "Travel Case",
      category: "accesories",
      image: "/images/products/product2.jpg",
      price: 80,
      countInStock: 0,
      rating: 4,
      numReviews: 9,
      description: "Travel Case with wheels, high quality product",
    },
  ],
};
